SuadeLabs/fire

- documentation/properties/credit_support_types.md
- documentation/properties/mna_id.md
- examples/README.md
- examples/derivative_payables_with_vm_posted.json
- examples/derivative_receivables_with_vm_received.json
- examples/derivative_unmargined_itm.json
- examples/derivative_unmargined_otm.json
- examples/derivative_with_im_facing_ccp.json
- examples/derivative_with_im_facing_ci.json
- examples/derivative_with_initial_margin.json
- examples/master_netting_agreement_with_csa.json
- examples/master_netting_agreement_without_csa.json
- examples/security_collateral_posted_ccp_non_deriv.json
- examples/variation_margin_bond_posted.json
- examples/variation_margin_bond_received.json
- examples/variation_margin_cash_posted.json
- examples/variation_margin_cash_received.json
Adds examples for derivatives and agreements
> Add derivatives and margins documentation

- v1-dev/account.json
* Align with loan schema
* Example of where it could be used: finrep-f14
> Add acc_fv_change_before_taxes to account schema

- documentation/properties/fvh_level.md
- v1-dev/account.json
- v1-dev/derivative.json
- v1-dev/loan.json
- v1-dev/security.json
* Products: account, derivative, loan, security
* Documentation: quotes from IFRS13
> Add fair value hierarchy to products

- documentation/properties/implied_volatility.md
- documentation/properties/purpose.md
- documentation/properties/regulatory_book.md
- v1-dev/account.json
- v1-dev/collateral.json
- v1-dev/common.json
- v1-dev/derivative.json
- v1-dev/derivative_cash_flow.json
- v1-dev/loan.json
- v1-dev/security.json
Update schemas for regulatory book and synthetic derivatives
> Update derivatives and underlyings

- documentation/properties/margin_frequency.md
- documentation/properties/start_date.md
- v1-dev/agreement.json
- v1-dev/derivative.json
added daily_settled to Agreement margin_frequency
amended definition of start_date to include derivatve effective date
> Added daily_settled to Agreement margin_frequency

- documentation/properties/incurred_cva.md
- documentation/properties/margin_frequency.md
- v1-dev/agreement.json
- added incurred_cva to agreement schema
- created incurred_cva.md
> added incurred_cva to agreement schema; created incurrred_cva.md

- documentation/properties/annual_debit_turnover.md
- documentation/properties/purpose.md
- v1-dev/customer.json
- v1-dev/loan.json
As discussed. This is the change specific to the BoE LN reports.
> Add annual debit turnover

- documentation/properties/capital_tier.md
- v1-dev/security.json
Additions of the following enum items to the capital_tier property of the security schema 
ce_tier_1_grandfathered
at_1_grandfathered
t2_grandfathered:
> added capital_tier property

- documentation/properties/purpose.md
- documentation/properties/type.md
- v1-dev/loan.json
1. Added project_finance to loan purposes
2. moved the associated description found in type.md to purpose.md
> add project_finance to loan purpose

- tests/test_schemas.py
Update to test_schema_properties_are_alphabetical to test list versus list rather than dictionary versus list
> Correct test_schemas

- tests/test_schemas.py
- v1-dev/reporter.json
Removed relationship property as this was incorrectly overriding what was already declared in entity.
> remove relationship property from reporter

- documentation/properties/type.md
- v1-dev/account.json
add third party savings accounts to the account type enum
> add third party savings to account type enum

- v1-dev/adjustment.json
Closes https://github.com/SuadeLabs/fire/issues/147
> Adjustments: make text and amount mutually exclusive

- documentation/properties/purpose.md
- v1-dev/account.json
New property for FINREP reporting of income tax for items that may be reclassified for profit/loss.
> added new reclass_tax property to purpose

- documentation/properties/last_drawdown_date.md
- documentation/properties/type.md
- v1-dev/loan.json
adding loan types reverse_mortgage and qualified_reverse_mortgage. added field last_drawdown_date to loan schema.
> update to loan schema

- documentation/properties/first_arrears_date.md
- v1-dev/account.json
- v1-dev/security.json
`first_arrears_date` attribute to be added to account and securities schema
> Add first_arrears_date to Account and Security schema

- v1-dev/loan_cash_flow.json
somehow we missed this from the original MR
> add loan_id to loan_cash_flow

- examples/fx_option_long_call.json
- examples/fx_option_long_put.json
- examples/fx_option_short_call.json
- examples/fx_option_short_put.json
add fx option examples:
- Long put
- Long call
- Short put
- Short call
> add fx option examples

- documentation/properties/naics_code.md
- documentation/properties/reversion_date.md
- documentation/properties/reversion_rate.md
- v1-dev/entity.json
- v1-dev/security.json
- Security shcema: `reversion_rate`, `reversion_date`  
- Entity schema: `naics_code`
> Entity: adds naics_code | Security: adds reversion_rate and reversion_date

- documentation/properties/type.md
Update description for collateral types;
- residential_property
- commercial_property
- multifamily
Also noticed on recent pull requests that **tests/test_docs.py::TestDocs::test_urls_in_docs** was failing, the link was previously [this](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02013R0575-20240101#:~:text=%E2%80%98clean%2Dup%20call,pre%2Dspecified%20level%3B), which is returning a 404, updated the link to reference the article mentioned in the docs (Art 242) [new-link](https://www.eba.europa.eu/regulation-and-policy/single-rulebook/interactive-single-rulebook/15998) to fix tests.
> Updating collateral type descriptions & fix tests

- requirements.txt
- tests/test_docs.py
As discussed, updated test to use httpx rather than grequests.
> Update test to use httpx instead of grequests

- documentation/properties/hqla_class.md
- v1-dev/security.json
- Added the `ineligible_non_op` enum under `hqla_class`
> Add the 'ineligible_non_op' enum under hqla_class

- documentation/properties/type.md
- v1-dev/loan.json
Addition of `education` loan type
> Addition of education loan type

- documentation/properties/type.md
- v1-dev/loan.json
Add commercial deposits to loan types
> Add cd to type enum on loan schema

- documentation/properties/credit_process.md
- v1-dev/loan.json
- Addition of the `credit_process` attribute to the loan schema
-  The `credit_process` attribute has the following enums
- `graded`
- `rated` 
- `scored`
- `delinquency_managed`
> Addition of credit_process attribute to the loan schema

- documentation/properties/econ_loss_retail.md
- documentation/properties/econ_loss_wholesale.md
- documentation/properties/fraud_loss_retail.md
- documentation/properties/purpose.md
- v1-dev/account.json
- v1-dev/loan.json
> 366 new attrs for osfi reports bd and bb -  follow up

- schemas/risk_rating.json
- v1-dev/risk_rating.json
changing type for id and adding version and source to schema
> updating id and source/version id

- documentation/properties/default_date.md
- documentation/properties/ead.md
- documentation/properties/last_recovery_date.md
- documentation/properties/last_write_off_date.md
- documentation/properties/resolution_date.md
- schemas/account.json
- schemas/loan.json
- v1-dev/account.json
- v1-dev/loan.json
Created new attributes "Date of Financial Institution's Write Off", "Date of Recovery", "Exposure at Default (EAD)", "Date of Resolution", and "Default Date" to accommodate the OSFI data requirement for OSFI reports BF,BG, DT3 and DT4
> new attrs for BH irb done

- schemas/account.json
- schemas/loan.json
- v1-dev/account.json
- v1-dev/loan.json
updating type for monetary type for ead
> updating num to int for monetary type

- schemas/batch.json
- schemas/collateral.json
- schemas/customer.json
- schemas/loan.json
- v1-dev/batch.json
- v1-dev/collateral.json
- v1-dev/customer.json
- v1-dev/loan.json
Spotted a few discrepancies in the schemas
> Consistent Schemas

- documentation/properties/bankruptcy_type.md
- documentation/properties/ead_irb_ec.md
- documentation/properties/lgd_irb.md
- documentation/properties/lgd_irb_ec.md
- documentation/properties/pd_irb.md
- documentation/properties/pd_irb_ec.md
- documentation/properties/review_date.md
- schemas/account.json
- schemas/customer.json
- schemas/derivative.json
- schemas/entity.json
- schemas/loan.json
- schemas/security.json
- v1-dev/account.json
- v1-dev/customer.json
- v1-dev/derivative.json
- v1-dev/entity.json
- v1-dev/loan.json
- v1-dev/security.json
Add new fields for economic capital calculations (ead_irb_ec, pd_irb_ec, lgd_irb_ec)
Add review_date and bankruptcy_type
> Add new loan account customer fields bf

- extensions/documentation/properties/int_reset_freq.md
- extensions/documentation/properties/orig_charge.md
- extensions/documentation/properties/orig_int_reset_freq.md
- extensions/documentation/properties/orig_spread.md
- extensions/documentation/properties/periodic_pay_cap.md
- extensions/documentation/properties/periodic_pay_floor.md
- extensions/documentation/properties/periodic_rate_cap.md
- extensions/documentation/properties/periodic_rate_floor.md
- extensions/schemas/collateral.json
- extensions/schemas/loan.json
Final batch of fire extension fixes. Batched into commits per the fix type, so best viewed individually.
> Final fire extension fixes

- documentation/properties/lgd_downturn.md
- documentation/properties/lgd_irb.md
- documentation/properties/lgd_irb_ec.md
- schemas/loan.json
- v1-dev/loan.json
Found a few proportions without corresponding limits included
> Enforce Proportions

- documentation/properties/type.md
- schemas/account.json
`financial_lease` added to type on account schema
Closes #456
> added new enum 'financial_lease' for account type

- documentation/properties/purpose.md
- schemas/account.json
> added new it_outsourcing enum for account purpose

- schemas/loan.json
- v1-dev/loan.json
sync enums for arrears_arrangement for loan and loan ext schemas
> sync enums for arrears_arrangement for loan and loan ext schemas

- documentation/properties/type.md
- schemas/account.json
- v1-dev/account.json
add `valuation_allowance` enum to `account` schema
> add valuation_allowance to account schema

- documentation/properties/mna_id.md
- documentation/properties/type.md
- schemas/account.json
- schemas/agreement.json
- schemas/loan.json
Adds mna_id to account and loan schema
Adds new agreement type "right_to_set_off"
> Add mna_id to account and loan schema + add new agreement type
