documentation/properties/purpose.md
v1-dev/account.json

2 new account purposes for BoE statistical reporting to record the following fees:
- fees on mortgage
- fees on unsecured personal loans

addition of 2 account purposes for fees

---

v1-dev/account.json
v1-dev/adjustment.json
v1-dev/agreement.json
v1-dev/collateral.json
v1-dev/customer.json
v1-dev/derivative.json
v1-dev/derivative_cash_flow.json
v1-dev/loan.json
v1-dev/loan_transaction.json
v1-dev/security.json

This will allow us to automatically distinguish between true integers and those which represent monetary values. Useful for e.g. ascertaining which fields exchange rates apply to.

Adds annotations to monetary types

---

v1-dev/account.json
v1-dev/common.json
v1-dev/loan.json

This update covers the case of overdraft accounts, which will need a ccf for the C07

Add ccf to accounts (for overdrafts)

---

documentation/properties/income_assessment.md
documentation/properties/single_income.md
run_tests.sh
v1-dev/loan.json

As discussed a while back, this will prevent the need for multiple loan customers and along with "ref_income_amount", allow more consistent definitions vs liquidity.

Add single_income field for loans

---

documentation/properties/purpose.md
v1-dev/account.json

Add a new Account Purpose enum as cf_hedge_reclass to capture FINREP products that are used for cash flow hedging, but have been reclassified to profit and loss, equity, carry amount or other classifications

Add cf_hedge_reclass to Account Purpose enum

---

v1-dev/loan_transaction.json

There is no foreseeable case where a loan transaction should exist without a corresponding loan.

Make loan_id a required field for loan_transaction

---

documentation/properties/day_count_convention.md
v1-dev/account.json
v1-dev/common.json
v1-dev/loan.json
v1-dev/security.json

Add day-count convention to account, loan and security schemas. This is needed for cash flow calculation in calculating the amount of accrued interest or the present value.

Add day count convention attribute

---

documentation/properties/type.md
v1-dev/security.json

Adding new security type for permanent interest bearing shares (PIBS), this is to allow us to differentiate between PIBS vs unsecured bonds issued.

Add new security type for PIBS

---

documentation/properties/purpose.md
documentation/properties/type.md
v1-dev/security.json

It makes more sense to make OCIR a purpose rather than a type. 
This way, we can still keep track the underlying product type reserved for resolution event.

Change type=ocir to purpose=ocir

---

.travis.yml
random_fire_generator.py
tests/__init__.py
tests/test_docs.py
tests/test_schemas.py

Blacken files and add black python code format checker stage to CI pipeline.
So that there's going to be a common code style between the fire repo and its clients/users (where fire is a subrepo). And this code style match will be enforced in CI black check.
run `$black . ` locally and then run `$black . --check` in CI pipeline.

Add black check to ci pipeline and blacken python files

---

v1-dev/loan.json

Add cb_haircut to loan schema so that user can identify which loans are eligible for central bank under C66/PRA110. Similar to how cb_haircut is used in security schema.

Add cb_haircut to loan schema

---

documentation/properties/type.md
tests/test_docs.py
v1-dev/collateral.json

adding capability to add a security to a loan via the collateral schema. allows for many to many mappings of loans and security collateral.

adding collateral type security, security id in collateral schema

---

documentation/properties/type.md
v1-dev/account.json

We need a way to have different types of deferred tax liabilities/assets for both finrep and BCAR
e.g. Deferred tax liabilities relating to computer software we can map as type = deferred_tax, purpose = computer_software
Seems we need to be able to distinguish between a few different purposes of deferred tax accounts (goodwill, CS etc)

deferred_tax as child of deferred

---

documentation/properties/amount.md
documentation/properties/date.md
documentation/properties/id.md
documentation/properties/source.md
documentation/properties/type.md
documentation/properties/version_id.md
tests/test_schemas.py
v1-dev/loan_cash_flow.json

Adds a simple loan cash flow schema (experimental).
Notes: I've deliberately left _out_ the currency code from this schema on the basis that a cash flow should not exist without a corresponding loan, and it should be denominated in the currency of the underlying loan.
Things will get _really_ complicated if we allow multiple cash flows for the same loan denominated in different currencies.

feat: add loan cash flow schema

---

examples/cds_index.json
examples/cds_single_name.json

The FIRE documentation for CDS Index and Single name should be updated to include the field "delta" as this used to determine the position long typically delta '-1' or short '1'. Both of the JSON files are short in this case.

addition of delta

---

v1-dev/loan_cash_flow.json

This is required for the cash flow to be a stand-alone item (and generally most of our systems set up to deal with monetary fields is ill-suited to having the currency code on a joined model).
Good practice (i.e. good data quality) should require that the currency code of the cash flow is the same as that of the underlying loan.

Add currency code to loan cash flow schema

---

documentation/properties/cr_approach.md
v1-dev/common.json

adding new approaches for equity in funds

adding new eif approaches

---

documentation/properties/status.md
v1-dev/derivative.json
v1-dev/security.json

Corresponds to the following GL issues; [one](https://gitlab.suade.io/suade/customers/-/issues/761) & [two](https://gitlab.suade.io/suade/Services/-/issues/15590). Regulations can be found [here](https://www.bis.org/basel_framework/chapter/CRE/70.htm).
Proposal to add a new enum to security/ derivative status under the **unsettled** enum as there are specific reports where this distinction is referenced.
For example C11.00 Settlement/Delivery Risk, we have the note from [here - page 135](https://www.bankofengland.co.uk/-/media/boe/files/prudential-regulation/regulatory-reporting/banking/corep-own-funds-instructions.pdf)
> 105.Note that own funds requirements for free deliveries as laid down in Article 379
CRR are not within the scope of the CR SETT template. Those own funds
requirements …

New status enum under unsettled

---

documentation/properties/type.md
v1-dev/security.json

Proposal to add new main_index_equity as a child of the equity security type.
The main_index_equity sub-type is used to identify equities that are constituents of a main index for the purposes of applying a volatility adjustment in line with [Article 224](https://www.eba.europa.eu/regulation-and-policy/single-rulebook/interactive-single-rulebook/16006). 
Previously in order to map these products, the **product_name** field included the main index name, but this overlaps with the rationale and benefit behind this property as firms may have pre-existing designation for the **product_name**. 
Refers to this GL [issue](https://gitlab.suade.io/suade/Services/-/issues/15656)

Add new enum 'main_index_equity' under security type equity

---

documentation/properties/minimum_balance.md
v1-dev/account.json
v1-dev/loan.json

Updating FIRE attribute to not specifically be denominated in `_EUR`. This is to allow users to populate minimum balance values in currencies other than EUR.
`minimum_balance_eur` will be deprecated on a later date.

Add `minimum_balance` to Account and Loan schema

---

documentation/properties/cum_write_offs.md
v1-dev/loan.json

I have created a new column "cum_write_offs" on the loans schema. This is concerned with cases where one loan was partially written off and retains an impairment type individual or collective. Currently, "Write_offs" are identified via Loans schema column "Impairment_type", where there's also gathered information on "Collective and "Individual" allowances.

addition of new cum_write_off column

---

documentation/properties/type.md

- Updated the definition of the cash_ratio_deposit enum to reflect the changes implemented by the BoE on that scheme.
- The BoE announced on 1 March 2024 the transition from the Cash ratio deposit (CRD) scheme to the Bank of England Levy ("the Levy"). According to the amendments made to the Bank of England Act 1998, the CRD scheme is no longer in effect and has been omitted and replaced with "the levy".

Update cash ratio deposit definition

---

documentation/properties/type.md
v1-dev/security.json

adding new type  "cb_restricted_reserve" under the Security schema for central bank reserves which are not liquid based on Article 7 (2) and not withdrawable and Article 10 (1)(b)(iii) of the Commission Delegated Regulation (EU) 2015/61 to supplement Regulation (EU) No 575/2013.

add new purpose  under security schema

---

documentation/properties/type.md
v1-dev/collateral.json
v1-dev/loan.json

- Addition of the `new_auto` and `used_auto` enums in the loan type schema, which are children of the `auto` loan type
- Addition of the `auto` collateral type

Addition of auto loan children types and auto collateral type

---

documentation/properties/birr_curve_id.md
documentation/properties/type.md
schemas/curve.json
schemas/entity.json
v1-dev/curve.json
v1-dev/entity.json

- Added `risk_rating` as a new curve type
- Modified the `value` field to be type-conditional:
- String type for `risk_rating` curves
- Number type for all other curve types (`behavioral`, `rate`, `volatility`)
- Expanded the `reference` enum to include more granular time periods:
- Added monthly periods up to 36 months
- Added quarterly periods up to 36 months
- Kept existing special periods (`o_n`, `1w`)
- Added new `birr_curve_id` property to link entities to their historical risk rating curves
- The property references a curve of type 'risk_rating' that contains historical BIRR identifiers
- Created new documentation for `birr_curve_id` property
- Clarified that curve values for risk ratings contain BIRR identifiers
- Added examples showing proper usage and data structure
These …

feat(curve): add risk rating as a type to curve schema
